--[[
**********************************************
  
  PreserveVar.lua
  (c) Jeroen Broks, 2015, 2016, All Rights Reserved.
  
  This file contains material that is related 
  to a storyline that is which is strictly
  copyrighted to Jeroen Broks.
  
  This file may only be used in an unmodified
  form with an unmodified version of the 
  software this file belongs to.
  
  You may use this file for your study to see
  how I solved certain things in the creation
  of this project to see if you find valuable
  leads for the creation of your own.
  
  Mostly this file comes along with a project
  that is for most part released under an
  open source license and that means that if
  you use that code with this file removed
  from it, you can use it under that license.
  Please check out the other files to find out
  which license applies.
  This file comes 'as-is' and in no possible
  way the author can be held responsible of
  any form of damages that may occur due to 
  the usage of this file
  
  
 **********************************************
 
version: 16.06.15
]]
-- This file is automatically generated from data.
-- When starting the new game+ this file determines which files will be transferred


ret = {
	fixed = {
		"$CTIME",
		"$LANG",
		"%PLAYTIME",
		"%PLAYTIME.SEC",
		"%SKILL",
		"%WENDICKA.NEED",
		"%AURINAS",
		"%COMBATSTAT.KILLS",
		"%COMBATSTAT.VICTORIES",
		"%KILLS.NEED",
		"%KILLS.DONE",
		"%WENDICKA.DONE",
		"&SYS.ABLPOWERUPFIXED",
		"%AURINACREDITS",
		"%AURINARATE",
		"%AURINAREQ",
		"%CASH",
		"%TERMINAL.SAVE",
		"$HAWKMUSIC",
		"%ARINAREQ",
		"%CASHSPENT4RATE",
		"%CASHTOTALSPENT",
		"&SUPAQUAL",
		"&TUTORIAL.BAGSFULL",
		"%AURINAEXCHANGED",
		"%FOXY.USED",
		"%UPGRADES.CRYSTAL",
		"%UPGRADES.WENDICKA",
		"%UPGRADES.FOXY",
		"%UPGRADES.XENOBI",
		"%UPGRADES.YIRL",
		"%TREASURE_RATE[Special Item 1B3E86B6]",
		"%TREASURE_RATE[Special Item 16C91EA5]",
		"%TREASURE_RATE[Special Item 16C94499]",
		"%TREASURE_RATE[Special Item 16CAA2ED]",
		"%TREASURE_RATE[Special Item 16CAF652]",
		"%TREASURE_RATE[Special Item 16CB4472]",
		"%SHILDERS",
		"%UPGRADES.ROLF"},

	prefix = {
		"$CTIME",
		"$LANG",
		"%PLAYTIME",
		"%PLAYTIME.SEC",
		"%SKILL",
		"%WENDICKA.NEED",
		"%AURINAS",
		"%COMBATSTAT.KILLS",
		"%COMBATSTAT.VICTORIES",
		"%KILLS.NEED",
		"%KILLS.DONE",
		"%WENDICKA.DONE",
		"&SYS.ABLPOWERUPFIXED",
		"%AURINACREDITS",
		"%AURINARATE",
		"%AURINAREQ",
		"%CASH",
		"%TERMINAL.SAVE",
		"$HAWKMUSIC",
		"%ARINAREQ",
		"%CASHSPENT4RATE",
		"%CASHTOTALSPENT",
		"&SUPAQUAL",
		"&TUTORIAL.BAGSFULL",
		"%AURINAEXCHANGED",
		"%FOXY.USED",
		"%UPGRADES.CRYSTAL",
		"%UPGRADES.WENDICKA",
		"%UPGRADES.FOXY",
		"%UPGRADES.XENOBI",
		"%UPGRADES.YIRL",
		"%TREASURE_RATE[Special Item 1B3E86B6]",
		"%TREASURE_RATE[Special Item 16C91EA5]",
		"%TREASURE_RATE[Special Item 16C94499]",
		"%TREASURE_RATE[Special Item 16CAA2ED]",
		"%TREASURE_RATE[Special Item 16CAF652]",
		"%TREASURE_RATE[Special Item 16CB4472]",
		"%SHILDERS",
		"%UPGRADES.ROLF",
		"<",
		"%PLAYTIME.",
		"&TUT.",
		"%ABL.USED.",
		"&ANNOUNCEDSECRET.",
		"%VAULT.",
		"&VAULT."}}


return ret
