ret = {
	["ABL_AP"] = 0,
	["ABL_Pose"] = "Cast",
	["APRecover"] = 100,
	["APRecoverType"] = "Percent",
	["ActSpeed"] = 250,
	["AttackElement"] = "Non-Elemental",
	["AttackStat"] = "Strength",
	["Buff_AP"] = -10,
	["Buff_Accuracy"] = -5,
	["Buff_Agility"] = -5,
	["Buff_Defense"] = -25,
	["Buff_Evasion"] = -100,
	["Buff_HP"] = -20,
	["Buff_Resistance"] = -25,
	["Buff_Strength"] = -5,
	["Buff_Will"] = -5,
	["CauseAmnesia"] = true,
	["CauseBagLock"] = true,
	["CauseConfusion"] = true,
	["CauseDisease"] = true,
	["CauseHandicapped"] = true,
	["CauseParalysis"] = true,
	["CausePoison"] = true,
	["CauseSleep"] = true,
	["CauseTerrified"] = true,
	["DefenseStat"] = "Defense",
	["Healing"] = 100,
	["HealingType"] = "Percent",
	["Icon"] = "GFX/Elements/Dark.png",
	["ItemType"] = "Consumable",
	["Name"] = "Cursed Healing",
	["Target"] = "1F",
	["UseCombat"] = true,
	["UseField"] = true}

return ret

-- This file is an automatically generated file!

