--[[
	Generated by Foe Editor
	(c) Jeroen P. Broks
	If this file has any references at all to the story line
	or any of its characters it may only be distributed in an
	unmodified form with an unmodified version of the game

	If this file has no references at all, you may
	use it under the terms of the zlib license!
]]


-- Version 17.01.07



Data = {
	Name = "Super Zombie",
	Desc = "Yikes, this one is STRONG!",
	ImageFile = "Boss/SuperZombie.png",
	AI = "Default",
	Boss = true,
	EleRes_Fire = 6,
	EleRes_Wind = 6,
	EleRes_Water = 6,
	EleRes_Earth = 6,
	EleRes_Frost = 6,
	EleRes_Lightning = 2,
	EleRes_Light = 1,
	EleRes_Dark = 6,
	EleRes_Healing = 1,
	EleRes_DarkHealing = 6,
	Stat = {
		["Strength"] = {1,600},
		["Defense"] = {0,200},
		["Will"] = {1,600},
		["Resistance"] = {1,200},
		["Agility"] = {1,222},
		["Accuracy"] = {1,600},
		["Evasion"] = {1,5},
		["HP"] = {20,1500},
		["AP"] = {0,0},
		["LevelRange"] = {1,150},
},
	StatusResistance = {
		["Poison"] = 100   --[[ #1 ]],
		["Paralysis"] = 100   --[[ #2 ]],
		["Disease"] = 100   --[[ #3 ]],
		["Will"] = 100   --[[ #4 ]],
		["Block"] = 100   --[[ #5 ]],
		["Death"] = 100   --[[ #6 ]],
		["Damned"] = 100   --[[ #7 ]],
	},
	Acts = {}, -- Data itself defined below
	ActMinLevel = {}, -- Data itself defined below
	ItemDrop = {}, -- Data itself defined below
	ItemSteal = {} -- Data itself definded below
}


local temp


Data.ActMinLevel["Sys.Attack"] = 1		for ak=1,100 do table.insert(Data.Acts,"Sys.Attack") end
Data.ActMinLevel["Abl.ABL_EXHURU_BATTLECRY"] = 0		for ak=1,5 do table.insert(Data.Acts,"Abl.ABL_EXHURU_BATTLECRY") end
Data.ActMinLevel["Abl.ABL_EXHURU_CONCENTRATE"] = 100		for ak=1,1 do table.insert(Data.Acts,"Abl.ABL_EXHURU_CONCENTRATE") end
Data.ActMinLevel["Abl.ABL_EXHURU_NELJA"] = 200		for ak=1,1 do table.insert(Data.Acts,"Abl.ABL_EXHURU_NELJA") end
Data.ActMinLevel["Abl.ABL_FOE_DEATH"] = 5		for ak=1,1 do table.insert(Data.Acts,"Abl.ABL_FOE_DEATH") end
Data.ActMinLevel["Abl.ABL_FOE_DEMON_SOUL_BREAKER"] = 1		for ak=1,5 do table.insert(Data.Acts,"Abl.ABL_FOE_DEMON_SOUL_BREAKER") end
Data.ActMinLevel["Abl.ABL_FOE_FEAR"] = 1		for ak=1,1 do table.insert(Data.Acts,"Abl.ABL_FOE_FEAR") end
Data.ActMinLevel["Abl.ABL_FOE_HORROR"] = 1		for ak=1,4 do table.insert(Data.Acts,"Abl.ABL_FOE_HORROR") end
Data.ActMinLevel["Abl.ABL_FOE_IDDQD"] = 500		for ak=1,1 do table.insert(Data.Acts,"Abl.ABL_FOE_IDDQD") end
Data.ActMinLevel["Abl.ABL_FOE_ULTRASONIC"] = 10000		for ak=1,1 do table.insert(Data.Acts,"Abl.ABL_FOE_ULTRASONIC") end
Data.ActMinLevel["Abl.ABL_ROTTEN_BREATH"] = 100		for ak=1,1 do table.insert(Data.Acts,"Abl.ABL_ROTTEN_BREATH") end
temp = { ITM='ITM_PHAN_LEVELAPPLE', LVL=650, VLT=false }
for ak=1,650 do table.insert(Data.ItemDrop ,temp) end
for ak=1,650 do table.insert(Data.ItemSteal,temp) end


return Data
