ret = {
	"EXCALIBUR_HOME",
	"INTRO_SHIP_TRANSPORTER",
	"PROLOGUE_YAQIRPA",
	"TEST MAP",
	"EXCALIBUR_SICKBAY",
	"EXCALIBUR_ALLQUIET",
	"EXCALIBUR_KITCHEN",
	"TEST INSERTION AND ROTATION",
	"EXCALIBUR_UNDERATTACK",
	"EXCALIBUR_SECRETPASSAGE",
	"TEST COLOR AND ANIMATION",
	"EXCALIBUR_HANGAR",
	"HAWK",
	"LOSTPLANET_GRASSJUNGLE",
	"LOSTPLANET_GRASSJUNGLE_2",
	"TEST TRANSPORTERS",
	"LOSTPLANET_BONUS_DARK_CAVES_OF_SHILINGTON",
	"LOSTPLANET_GRASSJUNGLE_3",
	"LOSTPLANET_PUB_OUTSIDE"}

return ret