RPGChar.SetData("Foxy","INVITEM1","HEALINGCAPSULE")
RPGStat.SetStat("Foxy","INVAMNT1",3)
RPGChar.SetData("Foxy","INVITEM2","FIRSTAIDKIT")
RPGStat.SetStat("Foxy","INVAMNT2",7)
RPGChar.SetData("Foxy","INVITEM2","ANTIDOTE")
RPGStat.SetStat("Foxy","INVAMNT2",8)
RPGChar.DefStat("Foxy","AMMO_BASE",6)
RPGChar.DefStat("Foxy","Level",30/skill)
Console.Write("Let's welcome Foxy!",0,255,0)