--[[
  ABL_FOE_PHOTON.lua
  
  version: 15.09.13
  Copyright (C) 2015 Jeroen P. Broks
  This software is provided 'as-is', without any express or implied
  warranty.  In no event will the authors be held liable for any damages
  arising from the use of this software.
  Permission is granted to anyone to use this software for any purpose,
  including commercial applications, and to alter it and redistribute it
  freely, subject to the following restrictions:
  1. The origin of this software must not be misrepresented; you must not
     claim that you wrote the original software. If you use this software
     in a product, an acknowledgment in the product documentation would be
     appreciated but is not required.
  2. Altered source versions must be plainly marked as such, and must not be
     misrepresented as being the original software.
  3. This notice may not be removed or altered from any source distribution.
]]
-- This file has be generated by Tricky's MyData
-- 13 Sep 2015; 01:24:50
-- License: If stripped from any reference to the story line and its characters, this file becomes zLib
	ret = {
		["ABL_AP"] = 0,
		["ABL_APCut"] = 0,
		["ABL_Cancel"] = 0,
		["ABL_DblPower"] = 0,
		["ABL_DblSpeed"] = 0,
		["ABL_Instant"] = 0,
		["ABL_Speed"] = 250,
		["ARM_Hit%"] = 0,
		["ARM_MaxAmmo"] = 0,
		["ARM_XPower"] = 0,
		["ActSpeed"] = 250,
		["AniIsEffectScript"] = false,
		["AniScriptDefaultPath"] = true,
		["AniScriptFile"] = "@COMBAT@ShootPhoton",
		["AttackElement"] = "Non-Elemental",
		["AttackPower"] = 100,
		["AttackStat"] = "Strength",
		["CauseAmnesia"] = false,
		["CauseBagLock"] = false,
		["CauseConfusion"] = false,
		["CauseDisease"] = false,
		["CauseHandicapped"] = false,
		["CauseParalysis"] = false,
		["CausePoison"] = false,
		["CauseSleep"] = false,
		["CauseTerrified"] = false,
		["CureAmnesia"] = false,
		["CureBagLock"] = false,
		["CureConfusion"] = false,
		["CureDeathFull"] = false,
		["CureDeathOne"] = false,
		["CureDisease"] = false,
		["CureHandicapped"] = false,
		["CureParalysis"] = false,
		["CurePoison"] = false,
		["CureSleep"] = false,
		["CureTerrified"] = false,
		["DefenseStat"] = "Defense",
		["Description"] = "",
		["EffectScriptDefaultPath"] = true,
		["EffectScriptFile"] = "",
		["EffectScriptFunction"] = "EFFECT_MAIN",
		["Healing"] = 0,
		["HealingType"] = "Absolute",
		["Icon"] = "GFX/Abilities/Gun.png",
		["ItemType"] = "Consumable",
		["Name"] = "Photon Gun",
		["Target"] = "1F",
		["UseCombat"] = true,
		["UseField"] = true}

return ret
