--[[
  ITM_ANTIDOTE.lua
  Version: 15.09.17
  Copyright (C) 2015 Jeroen Petrus Broks
  
  ===========================
  This file is part of a project related to the Phantasar Chronicles or another
  series or saga which is property of Jeroen P. Broks.
  This means that it may contain references to a story-line plus characters
  which are property of Jeroen Broks. These references may only be distributed
  along with an unmodified version of the game. 
  
  As soon as you remove or replace ALL references to the storyline or character
  references, or any termology specifically set up for the Phantasar universe,
  or any other univers a story of Jeroen P. Broks is set up for,
  the restrictions of this file are removed and will automatically become
  zLib licensed (see below).
  
  Please note that doing so counts as a modification and must be marked as such
  in accordance to the zLib license.
  ===========================
  zLib license terms:
  This software is provided 'as-is', without any express or implied
  warranty.  In no event will the authors be held liable for any damages
  arising from the use of this software.
  Permission is granted to anyone to use this software for any purpose,
  including commercial applications, and to alter it and redistribute it
  freely, subject to the following restrictions:
  1. The origin of this software must not be misrepresented; you must not
     claim that you wrote the original software. If you use this software
     in a product, an acknowledgment in the product documentation would be
     appreciated but is not required.
  2. Altered source versions must be plainly marked as such, and must not be
     misrepresented as being the original software.
  3. This notice may not be removed or altered from any source distribution.
]]
-- This file has be generated by Tricky's MyData
-- 17 Sep 2015; 11:08:43
-- License: If stripped from any reference to the story line and its characters, this file becomes zLib
	ret = {
		["ABL_AP"] = 0,
		["ABL_APCut"] = 0,
		["ABL_Cancel"] = 0,
		["ABL_DblPower"] = 0,
		["ABL_DblSpeed"] = 0,
		["ABL_Instant"] = 0,
		["ABL_Speed"] = 0,
		["ARM_Hit%"] = 0,
		["ARM_MaxAmmo"] = 0,
		["ARM_Weight"] = 0,
		["ARM_XPower"] = 0,
		["ActSpeed"] = 250,
		["AniIsEffectScript"] = false,
		["AniScriptDefaultPath"] = true,
		["AniScriptFile"] = "",
		["AttackElement"] = "Non-Elemental",
		["AttackPower"] = 0,
		["AttackStat"] = "Strength",
		["CauseAmnesia"] = false,
		["CauseBagLock"] = false,
		["CauseConfusion"] = false,
		["CauseDisease"] = false,
		["CauseHandicapped"] = false,
		["CauseParalysis"] = false,
		["CausePoison"] = false,
		["CauseSleep"] = false,
		["CauseTerrified"] = false,
		["CureAmnesia"] = false,
		["CureBagLock"] = false,
		["CureConfusion"] = false,
		["CureDeathFull"] = false,
		["CureDeathOne"] = false,
		["CureDisease"] = true,
		["CureHandicapped"] = false,
		["CureParalysis"] = false,
		["CurePoison"] = false,
		["CureSleep"] = false,
		["CureTerrified"] = false,
		["DefenseStat"] = "Defense",
		["Description"] = "Cures \"Poison\"",
		["EffectScriptDefaultPath"] = true,
		["EffectScriptFile"] = "",
		["EffectScriptFunction"] = "EFFECT_MAIN",
		["Healing"] = 0,
		["HealingType"] = "Absolute",
		["Icon"] = "GFX/Inventory/Green_tube.png",
		["ItemType"] = "Consumable",
		["Name"] = "Antidote",
		["PRICE_ARM_Hit%"] = 0,
		["PRICE_ARM_MaxAmmo"] = 0,
		["PRICE_ARM_XPower"] = 0,
		["Target"] = "1A",
		["UseCombat"] = true,
		["UseField"] = true}

return ret
