--[[
***********************************************************
ITM_ADHBANDAGE.lua
This particular file has been released in the public domain
and is therefore free of any restriction. You are allowed
to credit me as the original author, but this is not 
required.
This file was setup/modified in: 
2015
If the law of your country does not support the concept
of a product being released in the public domain, while
the original author is still alive, or if his death was
not longer than 70 years ago, you can deem this file
"(c) Jeroen Broks - licensed under the CC0 License",
with basically comes down to the same lack of
restriction the public domain offers. (YAY!)
*********************************************************** 
Version 15.09.14
]]
-- This file has be generated by Tricky's MyData
-- 14 Sep 2015; 13:22:04
-- License: If stripped from any reference to the story line and its characters, this file becomes zLib
	ret = {
		["ABL_AP"] = 0,
		["ABL_APCut"] = 0,
		["ABL_Cancel"] = 0,
		["ABL_DblPower"] = 0,
		["ABL_DblSpeed"] = 0,
		["ABL_Instant"] = 0,
		["ABL_Speed"] = 0,
		["ARM_Hit%"] = 0,
		["ARM_MaxAmmo"] = 0,
		["ARM_XPower"] = 0,
		["ActSpeed"] = 400,
		["AniIsEffectScript"] = false,
		["AniScriptDefaultPath"] = true,
		["AniScriptFile"] = "",
		["AttackElement"] = "Non-Elemental",
		["AttackPower"] = 0,
		["AttackStat"] = "Strength",
		["CauseAmnesia"] = false,
		["CauseBagLock"] = false,
		["CauseConfusion"] = false,
		["CauseDisease"] = false,
		["CauseHandicapped"] = false,
		["CauseParalysis"] = false,
		["CausePoison"] = false,
		["CauseSleep"] = false,
		["CauseTerrified"] = false,
		["CureAmnesia"] = false,
		["CureBagLock"] = false,
		["CureConfusion"] = false,
		["CureDeathFull"] = false,
		["CureDeathOne"] = false,
		["CureDisease"] = false,
		["CureHandicapped"] = false,
		["CureParalysis"] = false,
		["CurePoison"] = false,
		["CureSleep"] = false,
		["CureTerrified"] = false,
		["DefenseStat"] = "Defense",
		["Description"] = "Heals 25 HP",
		["EffectScriptDefaultPath"] = true,
		["EffectScriptFile"] = "",
		["EffectScriptFunction"] = "EFFECT_MAIN",
		["Healing"] = 25,
		["HealingType"] = "Absolute",
		["Icon"] = "GFX/Inventory/Patch.png",
		["ItemType"] = "Consumable",
		["Name"] = "Adhesive Bandage",
		["Target"] = "1A",
		["UseCombat"] = true,
		["UseField"] = true}

return ret
