--[[
 **********************************************
  
  This file is part of a closed-source 
  project by Jeroen Petrus Broks and should
  therefore not be in your pocession without
  his permission which should be obtained 
  PRIOR to obtaining this file.
  
  You may not distribute this file under 
  any circumstances or distribute the 
  binary file it procudes by the use of 
  compiler software without PRIOR written
  permission from Jeroen P. Broks.
  
  If you did obtain this file in any way
  please remove it from your system and 
  notify Jeroen Broks you got it somehow. If
  you have downloaded it from a website 
  please notify the webmaster to remove it
  IMMEDIATELY!
  
  Thank you for your cooperation!
  
  
 **********************************************
ITM_KEY_YAQIRPA.lua
(c) 2015 Jeroen Petrus Broks
Version: 15.09.17
]]
-- This file has be generated by Tricky's MyData
-- 17 Sep 2015; 11:08:43
-- License: If stripped from any reference to the story line and its characters, this file becomes zLib
	ret = {
		["ABL_AP"] = 0,
		["ABL_APCut"] = 0,
		["ABL_Cancel"] = 0,
		["ABL_DblPower"] = 0,
		["ABL_DblSpeed"] = 0,
		["ABL_Instant"] = 0,
		["ABL_Speed"] = 0,
		["ARM_Hit%"] = 0,
		["ARM_MaxAmmo"] = 0,
		["ARM_Weight"] = 0,
		["ARM_XPower"] = 0,
		["ActSpeed"] = 250,
		["AniIsEffectScript"] = false,
		["AniScriptDefaultPath"] = true,
		["AniScriptFile"] = "",
		["AttackElement"] = "Non-Elemental",
		["AttackPower"] = 0,
		["AttackStat"] = "Strength",
		["CauseAmnesia"] = false,
		["CauseBagLock"] = false,
		["CauseConfusion"] = false,
		["CauseDisease"] = false,
		["CauseHandicapped"] = false,
		["CauseParalysis"] = false,
		["CausePoison"] = false,
		["CauseSleep"] = false,
		["CauseTerrified"] = false,
		["CureAmnesia"] = false,
		["CureBagLock"] = false,
		["CureConfusion"] = false,
		["CureDeathFull"] = false,
		["CureDeathOne"] = false,
		["CureDisease"] = false,
		["CureHandicapped"] = false,
		["CureParalysis"] = false,
		["CurePoison"] = false,
		["CureSleep"] = false,
		["CureTerrified"] = false,
		["DefenseStat"] = "Defense",
		["Description"] = "Grants access to the Yaqirpa Tower",
		["EffectScriptDefaultPath"] = true,
		["EffectScriptFile"] = "",
		["EffectScriptFunction"] = "EFFECT_MAIN",
		["Healing"] = 0,
		["HealingType"] = "Absolute",
		["Icon"] = "GFX/Inventory/Key.png",
		["ItemType"] = "KeyItem",
		["Name"] = "Gold Yaqirpa Key",
		["PRICE_ARM_Hit%"] = 0,
		["PRICE_ARM_MaxAmmo"] = 0,
		["PRICE_ARM_XPower"] = 0,
		["Target"] = "1F",
		["UseCombat"] = true,
		["UseField"] = true}

return ret
